name: Issue Actions

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  print_issue:
    name: Print Issue
    steps:
      - name: Print Issue Number
        run: echo "Issue Number: ${{ github.event.action }}"
