name: Issue Actions

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  print_issue:
    name: Print Issue
    runs-on: ubuntu-latest
    steps:
      - name: Print Issue Number
        run: echo "Issue Number: ${{ github.event.issue.number }}"
