name: Issue Actions

on:
  issues:
    types:
      - labeled

jobs:
  print_issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'printme' }}
    steps:
      - name: Print issue number
        run: echo 'Hi ${{ github.event.issue.number }}'
