name: Issue Actions

on:
  issues:
    types:
      - labeled

jobs:
  print_issue:
    name: Print Issue
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'printme' }}
    steps:
      - name: Print issue body
        run: echo '${{ github.event.issue.body }}'
