name: Issue Actions

on:
  issues:
    types:
      - labeled

jobs:
  print_issue:
    name: Print Issue
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'printme' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          ruby-version-constraint: "~>"
      - name: Print parsed issue
        run: ruby ./scripts/print-issue.rb '${{ github.event.issue.body }}'
